name: Linux Kernel Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "ericvh/for-next" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    container:
      image: ghcr.io/v9fs/docker:latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: mkdir -p .build && make O=.build defconfig
    - name: make
      run: make -j16 O=.build
  
